// web/src/views/common/confirmOrder.vue
// +----------------------------------------------------------------------
// | LikeShop100%开源免费商用电商系统
// +----------------------------------------------------------------------
// | 欢迎阅读学习系统程序代码，建议反馈是我们前进的动力
// | 开源版本可自由商用，可去除界面版权logo
// | 商业版本务必购买商业授权，以免引起法律纠纷
// | 禁止对系统程序代码以任何目的，任何形式的再发布
// | Gitee下载：https://gitee.com/likemarket/likeshopv2
// | 访问官网：https://www.likemarket.net
// | 访问社区：https://home.likemarket.net
// | 访问手册：http://doc.likemarket.net
// | 微信公众号：好象科技
// | 好象科技开发团队 版权所有 拥有最终解释权
// +----------------------------------------------------------------------
// | Author: LikeShopTeam
// +----------------------------------------------------------------------


<template>
    <div class="confirm-order">
        <div class="confirm-con">
            <div class="address-wrap row contain" @click="onSelectAddress">
                <img class="icon mr10" src="@A/images/pay_address.png" />
                <div class="address">
                    <div class="black md" v-if="!address.contact">
                        设置收货地址
                    </div>
                    <div v-else>
                        <span class="name md mr10">{{ address.contact }}</span>
                        <span class="phone md">{{ address.telephone }}</span>
                        <div class="area sm mt10 lighter">
                            {{ address.province }} {{ address.city }}
                            {{ address.district }} {{ address.address }}
                        </div>
                    </div>
                </div>
                <img class="icon-sm ml10" src="@A/images/arrow_right.png" />
            </div>
            <div class="goods contain">
                <order-goods :list="goodsLists" />
                <div class="item row-between">
                    <div>配送方式</div>
                    <div>快递</div>
                </div>
                <div class="input">
                    <van-field
                        v-model="userRemark"
                        type="textarea"
                        rows="1"
                        :autosize="{ minHeight: 30, maxHeight: 80 }"
                        label="店铺留言"
                        placeholder="选填，请输入150字以内的文字留言"
                    />
                </div>
            </div>
            <div class="contain coupons">
                <div class="item row-between" @click="showCoupon = true">
                    <div>优惠券</div>
                    <div class="row">
                        <span v-if="orderInfo.discount_amount" class="primary"
                            >-￥{{ orderInfo.discount_amount }}</span
                        >
                        <span v-else class="muted md">请选择</span>
                        <img
                            class="icon-sm ml10"
                            src="@A/images/arrow_right.png"
                        />
                    </div>
                </div>
            </div>
            <div class="price contain">
                <div class="item row-between">
                    <div>商品金额</div>
                    <div>¥{{ orderInfo.total_goods_price }}</div>
                </div>
                <div class="item row-between">
                    <div>运费</div>
                    <div>¥{{ orderInfo.shipping_price }}</div>
                </div>
                <div class="item row-between" v-if="orderInfo.discount_amount">
                    <div>优惠券</div>
                    <div class="primary">-¥{{ orderInfo.discount_amount }}</div>
                </div>
            </div>
            <div class="pay-way contain">
                <div class="lighter title">支付方式</div>
                <van-radio-group
                    class="radio-group"
                    v-model="payWay"
                    :checked-color="primaryColor"
                >
                    <div
                        class="item row-between"
                        v-for="item in payWayArr"
                        :key="item.type"
                        @click="payWay = item.type"
                    >
                        <div class="row">
                            <img class="icon-lg mr10" :src="item.icon" />
                            <div class>
                                <div class="balck bt10">{{ item.name }}</div>
                                <div class="muted xs">
                                    {{ item.desc
                                    }}{{
                                        item.type == 3
                                            ? orderInfo.user_money
                                            : ""
                                    }}
                                </div>
                            </div>
                        </div>
                        <van-radio :name="item.type"></van-radio>
                    </div>
                </van-radio-group>
            </div>
        </div>
        <div class="footer bg-white row-between">
            <div class="all-price lg row">
                <span>合计：</span>
                <div class="primary row">
                    ￥
                    <price-slice :price="orderInfo.order_amount" />
                </div>
            </div>
            <button
                class="btn br60 white"
                size="md"
                hover-class="none"
                @click="onSubmitOrder"
            >
                提交订单
            </button>
        </div>
        <van-popup
            safe-area-inset-bottom
            class="coupon-popup"
            v-model="showCoupon"
            closeable
            round
            position="bottom"
            @close="onCloseCoupon"
        >
            <div class="title">优惠券</div>
            <van-tabs :active="popActive">
                <van-tab :title="`可使用优惠券 (${usableCoupon.length})`">
                    <coupon-popup
                        :list="usableCoupon"
                        :type="0"
                        @select="onSelectCoupon"
                    ></coupon-popup>
                </van-tab>
                <van-tab :title="`不可用优惠券 (${unusableCoupon.length})`">
                    <coupon-popup
                        :list="unusableCoupon"
                        :type="1"
                    ></coupon-popup>
                </van-tab>
            </van-tabs>
            <div
                class="bg-primary white br60 btn lg"
                size="md"
                @click="onCloseCoupon"
            >
                确认
            </div>
        </van-popup>
    </div>
</template>

<script>
import wx from "weixin-js-sdk";
import { orderBuy, getOrderCoupon } from "@/api/store";
import { prepay } from "@/api/app";
import OrderGoods from "@C/OrderGoods";
import CouponPopup from "@C/CouponPopup";
import { payWayType } from "@/utils/type";
import { wxPay } from "@/utils/wxjssdk";
import { Dialog } from 'vant';
export default {
    name: "confirmOrder",
    components: {
        OrderGoods,
        CouponPopup,
    },
    data() {
        return {
            address: {},
            orderInfo: {},
            userRemark: "",
            goodsLists: [],
            addressId: "",
            showCoupon: false,
            popActive: 0,
            usableCoupon: [],
            unusableCoupon: [],
            payWay: 1,
            payWayArr: [
                {
                    icon: require("@A/images/pay_wechat.png"),
                    name: "微信支付",
                    type: payWayType.wechat,
                    desc: "微信快捷支付",
                }
            ],
            showCoupon: false,
            useIntegral: 0,
        };
    },
    async created() {
        let { goods, type } = this.$route.query;
        this.addressId = this.$ls.get("addressid");
        this.$ls.remove("addressid");
        goods = JSON.parse(goods) || [];
        this.confirmType = type || "";
        this.goods = goods;
        await this.$getOrderCoupon();
        this.$orderBuy();
    },
    mounted() {
        this.$ls.remove("addressid");
    },
    methods: {
        onSelectAddress() {
            this.$router.push({
                name: "userAddress",
                query: {
                    type: 1,
                },
            });
        },
        onCloseCoupon() {
            this.showCoupon = false;
            this.$orderBuy();
        },
        onSelectCoupon(id) {
            this.couponId = id;
        },
        onSubmitOrder() {
            this.toast = this.$toast({
                type: "loading",
                message: "请稍等...",
                duration: 0,
            });
            this.$orderBuy("submit");
        },
        $getOrderCoupon() {
            return new Promise((resolve) => {
                console.log(this.goods);
                getOrderCoupon({
                    goods: this.goods,
                }).then((res) => {
                    if (res.code == 1) {
                        const { usable, unusable } = res.data;
                        this.usableCoupon = usable;
                        this.unusableCoupon = unusable;
                        resolve();
                    }
                });
            });
        },
        $orderBuy(action = "info") {
            let { address, userRemark } = this;
            let submitObj = {
                action,
                goods: this.goods,
                coupon_id: this.couponId
            };

            if (action == "info") {
                if (this.addressId) {
                    submitObj.address_id = this.addressId;
                }
            } else if (action == "submit") {
                submitObj.remark = userRemark;
                submitObj.address_id = address.id;
                submitObj.type = this.confirmType;
                submitObj.pay_way = this.payWay;
            }
            orderBuy(submitObj)
                .then((res) => {
                    if (res.code == 1) {
                        if (action == "info") {
                            let { address, goods_lists } = res.data;
                            this.address = address;
                            this.goodsLists = goods_lists;
                            this.orderInfo = res.data;
                            this.addressId = address.id;
                            return false;
                        } else if (action == "submit") {
                            let { order_id, type } = res.data;
                            this.tradeId = order_id;
                            this.type = type;
                            return prepay({
                                from: type,
                                order_id: order_id,
                            });
                        }
                    } else {
                        this.toast && this.toast.clear();
                        return false;
                    }
                })
                .then((res) => {
                    this.toast && this.toast.clear();
                    if (res.code == 1) {
                        let opt = res.data;
                        wxPay(opt)
                            .then((res) => {
                                this.$router.replace({
                                    name: "payResult",
                                    query: {
                                        id: this.tradeId,
                                        type: this.type,
                                    },
                                });
                            })
                            .catch(() => {
                                this.$router.replace({
                                    name: "userOrder",
                                });
                            });
                    } else if (res.code == 10001) {
                        this.$router.replace({
                            name: "payResult",
                            query: {
                                id: this.tradeId,
                                type: this.type,
                            },
                        });
                    }
                });
        },
    },
};
</script>

<style lang="scss" scoped>
.confirm-order {
    padding-bottom: 60px;
    .contain {
        margin: 10px 10px 0;
        border-radius: 7px;
        background-color: #fff;
        overflow: hidden;
    }
    .confirm-con {
        .img-line {
            height: 1.5px;
            width: 100%;
            display: block;
        }
        .address-wrap {
            height: 82px;
            padding: 0 10px;
            .address {
                flex: 1;
            }
        }
        .coupons {
            .item {
                height: 50px;
                padding: 0 10px;
            }
        }
        .goods {
            .title {
                padding: 11px 10px;
                border-bottom: $--border-base;
            }
            .all-num {
                padding: 11px 10px;
                border-bottom: 1px dotted $--border-color-base;
            }
            .input {
                .van-field {
                    padding: 13px 10px;
                }
            }
            .item {
                height: 50px;
                padding: 0 10px;
            }
        }
        .pay-way {
            .title {
                padding: 10px 10px;
            }
            .radio-group .item {
                height: 60px;
                padding: 0 10px;
            }
        }

        .price {
            padding: 0 10px;
            .item {
                height: 40px;
            }
        }
        .van-cell:after {
            border: none;
        }
    }
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        box-sizing: border-box;
        height: 50px;
        padding: 0 15px;
        .btn {
            background: linear-gradient(
                90deg,
                rgba(249, 95, 47, 1) 0%,
                rgba(255, 44, 60, 1) 100%
            );
            padding: 0 25px;
        }
    }

    .van-tag {
        width: 33px;
        height: 17px;
        font-size: 11px !important;
        background: linear-gradient(
            270deg,
            rgba(255, 80, 88, 1) 0%,
            rgba(255, 166, 48, 1) 100%
        );
        padding: 0 !important;
        justify-content: center;
    }
    .coupon-popup {
        .title {
            height: 50px;
            border-bottom: $--border-base;
            padding-left: 15px;
            font-weight: bold;
            line-height: 50px;
        }
        .btn {
            margin: 5px 10px;
            display: block;
            box-sizing: border-box;
            height: 37px;
            line-height: 37px;
            text-align: center;
        }
    }
}
</style>

// app/src/pages/common/ConfirmOrder.tsx
import React from 'react';
import { StyleSheet, Text, View, SafeAreaView, Image, FlatList } from 'react-native';
import Theme from '../../constraint/Theme'
import { contain, row, rowCenter, rowBetween, rowEnd, getImageSize } from '../../constraint/Style';
import { orderBuy, getOrderCoupon } from '../../api/store';
import { isSuccess } from '../../utils/request';
import PressButton from '../../components/main/PressButton';
import { ScreenProps } from '../../typing';
import { ScrollView, TextInput } from 'react-native-gesture-handler';
import AddressItem from '../../components/bussiness/AddressItem';
import OrderGoods from '../../components/bussiness/OrderGoods';
import PriceFormate from '../../components/bussiness/PriceFormate';
import { arrow_right, icon_balance, icon_help, icon_wechat } from '../../constraint/Image';
import LinearGradient from 'react-native-linear-gradient';
import { prepay } from '../../api/app';
import { WXPay } from '../../utils/wechat';
import { replace } from '../../utils/navigation';
import CheckBox from '../../components/bussiness/CheckBox';
import { registerEvent } from '../../utils/event';
import Popup from '../../components/main/Popup';
import ScrollableTabView from 'react-native-scrollable-tab-view';
import CustomTabBar from '../../components/main/CustomTabBar';
import CouponPopItem from '../../components/bussiness/CouponPopItem';
import { payWayType } from '../../utils/type';
import { Toast } from '@ant-design/react-native';
import Dialog from '../../components/main/Dialog';
// import Alipay from '@0x5e/react-native-alipay';


type ConfirmOrderProps = ScreenProps<'ConfirmOrder'>;


class ConfirmOrder extends React.Component<ConfirmOrderProps, any> {
    [x: string]: any;
    constructor(props: ConfirmOrderProps) {
        super(props)
        this.goods = props.route.params.goods
        this.confirmType = props.route.params.type
        this.state = {
            showCoupon: false,
            orderInfo: {},
            address: {},
            goodsList: [],
            usableCoupon: [],
            unusableCoupon: [],
            userRemark: '',
            payWayArr: [
                {
                    icon: icon_wechat,
                    name: '微信支付',
                    type: payWayType.wechat,
                    desc: '微信快捷支付'
                },
            ],
            payWay: payWayType.wechat,
            useIntegral: 0,
            showPoint: false
        }
    }
    UNSAFE_componentWillMount() {
        const { navigation } = this.props
        this.reflash = navigation.addListener('focus', () => {
            this._orderBuy()
        })
        this.listtenr = registerEvent('SELECT_ADDRESS', (id) => {
            this.addressId = id
        })
        this._getOrderCoupon()
    }
    componentWillUnmount() {
        this.reflash()
        this.listtenr.remove()
    }
    submitOrder() {
        this._orderBuy('submit')
    }
    changeIntegral() {
        const {useIntegral, orderInfo: {integral_limit, user_integral}} = this.state
        if(integral_limit > user_integral) return Toast.info("未满足使用条件")
        this.setState({
            useIntegral: useIntegral ? 0 : 1
        }, () => this._orderBuy())
      
    }
    goodsView() {
        const { goodsList, userRemark } = this.state
        return (
            <View style={styles.contain}>
                <OrderGoods goods={goodsList} />
                <View style={{ ...styles.conItem, ...rowBetween }}>
                    <Text>配送方式</Text>
                    <Text>快递</Text>
                </View>
                <View style={{ ...styles.conItem, ...row }}>
                    <Text style={{ width: 70 }}>买家留言</Text>
                    <TextInput style={{ padding: 0, height: '100%', flex: 1 }} placeholder="请添加备注（150字以内）" value={userRemark} onChangeText={(val) => this.setState({ userRemark: val })} />
                </View>
            </View>
        )
    }
    payWayView() {
        const { payWayArr, payWay, orderInfo } = this.state
        const items = payWayArr.map((item: any, index: any) => (
            <PressButton style={{ paddingHorizontal: 12, ...row, height: 60}} onPress={() => this.setState({payWay: item.type})}>
                <Image source={item.icon} style={getImageSize(24)} />
                <View style={{ marginLeft: 8, flex: 1 }}>
                    <Text>{ item.name }</Text>
                    <Text style={{marginTop: 5, color: Theme.color_text_muted, fontSize: Theme.font_size_xs}}></Text>
                </View>
                <CheckBox checked={item.type == payWay} />
            </PressButton>
        ))
        return (
            <View style={styles.contain}>
                <Text style={{ lineHeight: 35, paddingLeft: 12 }}>支付方式</Text>
                {items}
            </View>
        )
    }
    couponView() {
        const { orderInfo, useIntegral } = this.state
        return (
            <View style={styles.contain}>
                <PressButton style={{ ...row, ...styles.conItem, ...styles.borderBottom }} onPress={() => this.setState({ showCoupon: true })}>
                    <Text style={{ flex: 1 }}>优惠券</Text>
                    {orderInfo.discount_amount ? <Text style={{ color: Theme.brand_primary }}>-￥{orderInfo.discount_amount}</Text> :
                        <Text style={{ fontSize: Theme.font_size_sm, color: Theme.color_text_secondary }}>请选择</Text>}
                    <Image source={arrow_right} style={getImageSize(15)} />
                </PressButton>
            </View>
        )
    }
    priceView() {
        const { orderInfo: { shipping_price, total_goods_price, discount_amount, integral_amount } } = this.state
        return (
            <View style={{ ...styles.contain, paddingVertical: 15 }}>
                <View style={styles.priceItem}>
                    <Text>商品金额</Text>
                    <PriceFormate price={total_goods_price} />
                </View>
                <View style={styles.priceItem}>
                    <Text>运费</Text>
                    <PriceFormate price={shipping_price} />
                </View>
                {discount_amount ?<View style={styles.priceItem}>
                    <Text>优惠券</Text>
                    <PriceFormate color={Theme.brand_primary} price={discount_amount} showMinus={true}  />
                </View> : null}
                {integral_amount ? <View style={styles.priceItem}>
                    <Text>积分抵扣</Text>
                    <PriceFormate color={Theme.brand_primary} price={integral_amount} showMinus={true} />
                </View>: null}
            </View>
        )
    }
    _getOrderCoupon() {
        getOrderCoupon({
            goods: this.goods
        }).then((res: any) => {
            if (isSuccess(res)) {
                const { usable, unusable } = res.data
                this.setState({
                    usableCoupon: usable,
                    unusableCoupon: unusable
                })
            }
        })
    }
    async _orderBuy(action = 'info') {
        const { userRemark, payWay, useIntegral } = this.state

        //默认传参
        const submitObj: any = {
            action,
            goods: this.goods,
            address_id: this.addressId,
            coupon_id: this.couponId,
            use_integral: useIntegral
        }
        //提交订单参数
        if (action == 'submit') {
            submitObj.remark = userRemark
            submitObj.type = this.confirmType
            submitObj.pay_way = payWay
        }
        
        let order: any = await orderBuy(submitObj, true)
        if (!isSuccess(order)) return
        
        if (action == 'info') {
            //下单信息
            const { address, goods_lists } = order.data
            this.setState({
                orderInfo: order.data,
                address,
                goodsList: goods_lists
            })
        } else if (action == 'submit') {
            //下单成功
            let { order_id, type } = order.data
            let payOpt: any = await prepay({
                from: type,
                order_id: order_id
            }, true)
            if (isSuccess(payOpt)) {
                //微信支付
                let opt = payOpt.data
                WXPay(opt).then(() => {
                    replace('PayResult', {
                        id: order_id
                    })
                }).catch(() => {
                    replace('UserOrder')
                })
            }else if(payOpt.code == 10001) {
                //余额支付成功
                replace('PayResult', {
                    id: order_id
                })
            }else if(payOpt.code == 10002) {
                // await Alipay.pay(payOpt.data)
            }
        }
    }


    onCloseCoupon() {
        this.setState({
            showCoupon: false
        })
        this._orderBuy()
    }
    couponPopup() {
        const { usableCoupon, unusableCoupon, showCoupon } = this.state
        return (
            <Popup isVisible={showCoupon} position='bottom' closeable onClose={() => this.onCloseCoupon()}>
                <View style={{ height: 450 }}>
                    <Text style={{ fontSize: Theme.font_size_xl, fontWeight: 'bold', paddingLeft: 15, paddingVertical: 13 }}>优惠券</Text>
                    <ScrollableTabView
                        style={{ flex: 1, borderBottomWidth: 0 }}
                        prerenderingSiblingsNumber={1}
                        initialPage={0}
                        tabBarPosition='top'
                        renderTabBar={() => <CustomTabBar
                            activeColor={Theme.brand_primary}
                            inactiveColor={Theme.color_text_base}
                            activeTab={0}
                            tabUnderlineDefaultWidth={40}
                        />}
                    >
                        <CouponPopItem key={0} type={0} couponId={this.couponId} list={usableCoupon} tabLabel={`可使用优惠券 (${usableCoupon.length})`} onSelect={(id) => this.couponId = id} />
                        <CouponPopItem key={1} type={1} list={unusableCoupon} tabLabel={`不可使用优惠券 (${unusableCoupon.length})`} />
                    </ScrollableTabView>
                    <View style={{ paddingHorizontal: 12, paddingVertical: 3 }}>
                        <PressButton type="primary" size="md" round onPress={() => this.onCloseCoupon()}>确定</PressButton>
                    </View>
                </View>
            </Popup>
        )
    }
    pointPopup() {
        const {showPoint, orderInfo: {integral_config, integral_limit}} = this.state
        return (
            <Dialog   isVisible={showPoint} showCancelButton={false} onConfirm={() => this.setState({showPoint: false})}>
                <View style={{paddingHorizontal: 20}}>
                <Text style={{fontSize: Theme.font_size_lg, fontWeight: "bold", textAlign: "center", marginBottom: 30}}>积分使用说明</Text>
                    <Text style={{marginBottom: 20, color: Theme.color_text_secondary}}>·1积分可抵扣{integral_config}元</Text>
                    <Text style={{color: Theme.color_text_secondary}}>·单次扣减积分不能低于{integral_limit}积分</Text>
                </View>
            </Dialog>
        )
    }
    render() {
        const { address, goodsList, orderInfo } = this.state
        if (!orderInfo.address) return null
        return (
            <SafeAreaView style={contain}>
                <ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps='always'>
                    <View style={{paddingBottom: 20}}>
                    <AddressItem style={styles.contain} address={address} />
                    {this.goodsView()}
                    {this.couponView()}
                    {this.priceView()}
                    {this.payWayView()}
                    </View>
                </ScrollView>
                <View style={{ height: 50, backgroundColor: Theme.fill_base, ...rowBetween, paddingHorizontal: 12 }}>
                    <View style={row}>
                        <Text>合计：</Text>
                        <PriceFormate style={{ color: Theme.brand_primary, fontSize: 16 }} price={orderInfo.order_amount} />
                    </View>
                    <View style={{ borderRadius: Theme.radius_circel, backgroundColor: Theme.brand_primary }} >
                        <LinearGradient colors={['#F95F2F', '#FF2C3C']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={{ borderRadius: 30 }}>
                            <PressButton onPress={() => this.submitOrder()} style={{ width: 105, height: 37, ...rowCenter }} textStyle={{ color: Theme.fill_base }}>提交订单</PressButton>
                        </LinearGradient>
                    </View>
                </View>
                {this.couponPopup()}
                {this.pointPopup()}
            </SafeAreaView>
        );
    }
};

const styles = StyleSheet.create({

    contain: {
        borderRadius: 7,
        backgroundColor: Theme.fill_base,
        marginHorizontal: 10,
        marginTop: 10
    },
    conItem: {
        height: 50,
        paddingHorizontal: 12
    },
    borderBottom: {
        borderBottomWidth: 0.5,
        borderColor: Theme.border_color_base
    },
    priceItem: {
        paddingHorizontal: 10,
        ...rowBetween,
        marginTop: 10
    }
});

export default ConfirmOrder;
