// uniapp/pages/order_details/order_details.vue
// +----------------------------------------------------------------------
// | LikeShop100%开源免费商用电商系统
// +----------------------------------------------------------------------
// | 欢迎阅读学习系统程序代码，建议反馈是我们前进的动力
// | 开源版本可自由商用，可去除界面版权logo
// | 商业版本务必购买商业授权，以免引起法律纠纷
// | 禁止对系统程序代码以任何目的，任何形式的再发布
// | Gitee下载：https://gitee.com/likemarket/likeshopv2
// | 访问官网：https://www.likemarket.net
// | 访问社区：https://home.likemarket.net
// | 访问手册：http://doc.likemarket.net
// | 微信公众号：好象科技
// | 好象科技开发团队 版权所有 拥有最终解释权
// +----------------------------------------------------------------------
// | Author: LikeShopTeam
// +----------------------------------------------------------------------

<template>
<view>
<view class="order-details">
    <view class="header-bg"></view>
    <view class="header">
        <view class="item" v-if="orderDetail.order_status == 0">
            <view class="white lg mb10">等待买家付款</view>
       <!--     <view class="white sm row" v-if="cancelTime">支付剩余
                <van-count-down class="count-down" @finish="$getOrderDetail" :time="cancelTime" format="mm分ss秒"></van-count-down> 自动关闭</view> -->
        </view>
        <view class="item" v-if="orderDetail.order_status == 1">
            <view class="white lg mb10">等待商家发货</view>
            <view class="white sm">您的商品正在打包中，请耐心等待…</view>
        </view>
        <view class="item" v-if="orderDetail.order_status == 2">
            <view class="white lg mb10">已发货</view>
            <view class="white sm">您的商品正在路中，请耐心等待…</view>
        </view>
        <view class="item" v-if="orderDetail.order_status == 3">
            <view class="white lg mb10">已完成</view>
            <view class="white sm">商品已签收，期待再次购买！</view>
        </view>
        <view class="item" v-if="orderDetail.order_status == 4">
            <view class="white lg mb10">订单已关闭</view>
            <!-- <view class="white sm">原因：超时未支付</view> -->
        </view>
    </view>
    <view class="address-wrap row contain">
        <image class="icon-md mr20" src="/static/images/icon_address.png"></image>
        <view class="address">
            <view>
                <text class="name md mr10">{{orderDetail.consignee}}</text>
                <text class="phone md">{{orderDetail.mobile}}</text>
                <view class="area sm mt10 lighter">{{orderDetail.delivery_address}}</view>
            </view>
        </view>
    </view>
    <view class="goods contain">
        <order-goods :show-comment="orderDetail.comment_btn" link="true" :list="orderDetail.order_goods"></order-goods>
    </view>
    <view class="price contain">
        <view class="row-between">
            <view>商品金额</view>
            <view class="black">
                <price-format :price="orderDetail.goods_price"></price-format>
            </view>
        </view>
        <view class="row-between">
            <view>运费</view>
            <view class="black">+
                <price-format :price="orderDetail.shipping_price"></price-format>
            </view>
        </view>
        <view v-if="orderDetail.discount_amount != 0" class="row-between">
            <view>优惠券</view>
            <view class="primary">-
                <price-format :price="orderDetail.discount_amount"></price-format>
            </view>
        </view>
        <view class="row-end">
            <view class="lighter">实付金额：</view>
            <view class="primary xl">
                <price-format :first-size="34" :second-size="34" :price="orderDetail.order_amount"></price-format>
            </view>
        </view>
    </view>
    <view class="order-info contain">
        <view class="item row" style="align-items: flex-start;">
            <view class="title">买家留言</view>
            <view class="black">{{orderDetail.user_remark || '无'}}</view>
        </view>
    </view>
    <view class="order-info contain">
        <view class="item row">
            <view class="title">订单编号</view>
            <view class="black">{{orderDetail.order_sn}}</view>
        </view>
        <view class="item row">
            <view class="title">支付方式</view>
            <view class="black">{{orderDetail.pay_way_text}}</view>
        </view>
        <view class="item row">
            <view class="title">下单时间</view>
            <view class="black">{{orderDetail.create_time}}</view>
        </view>
        <view v-if="orderDetail.pay_time" class="item row">
            <view class="title">付款时间</view>
            <view class="black">{{orderDetail.pay_time}}</view>
        </view>
        <view v-if="orderDetail.shipping_time" class="item row">
            <view class="title">发货时间</view>
            <view class="black">{{orderDetail.shipping_time	}}</view>
        </view>
        <view v-if="orderDetail.confirm_take_time" class="item row">
            <view class="title">成交时间</view>
            <view class="black">{{orderDetail.confirm_take_time	}}</view>
        </view>
        <view v-if="orderDetail.cancel_time" class="item row">
            <view class="title">关闭时间</view>
            <view class="black">{{orderDetail.cancel_time}}</view>
        </view>

    </view>
    <view class="footer bg-white row fixed" v-if="orderDetail.cancel_btn || orderDetail.delivery_btn || orderDetail.take_btn || orderDetail.del_btn || orderDetail.pay_btn">
        <view style="flex: 1"></view>
        <view v-if="orderDetail.cancel_btn">
            <button size="sm" class="plain br60" hover-class="none" @tap="cancelOrder">取消订单</button>
        </view>
        <navigator v-if="orderDetail.delivery_btn" hover-class="none" :url="'/pages/goods_logistics/goods_logistics?id=' + orderDetail.id">
            <button size="sm" class="plain br60" hover-class="none">查看物流</button>
        </navigator>
        <view v-if="orderDetail.take_btn" class="ml20">
            <button size="sm" class="plain br60 primary red" hover-class="none" @tap.stop="comfirmOrder">确认收货</button>
        </view>
        <view v-if="orderDetail.del_btn">
            <button size="sm" class="plain br60" hover-class="none" @tap="delOrder">删除订单</button>
        </view>
        <view class="ml20" v-if="orderDetail.pay_btn">
            <button size="sm" class="bg-primary br60 white" @tap="payNow">立即付款</button>
        </view>
    </view>
</view>
<loading-view v-if="isFirstLoading"></loading-view>

</view>
</template>

<script>

import { getOrderDetail, cancelOrder, delOrder, confirmOrder } from '@/api/order';
import { prepay } from '@/api/app';
import { wxpay } from '@/utils/wxutil'

export default {
  data() {
    return {
      orderDetail: {},
      isFirstLoading: true,
      type: 0,
      cancelTime: 0,
      showCancel: ""
    };
  },

  components: {
  },
  props: {},

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    this.id = this.id ? this.id : options.id;
    this.getOrderDetailFun();
  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {},

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {},

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {},

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {},

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {},

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {},

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {},
  methods: {
    onShowDialog() {
      let {
        showCancel
      } = this;
      this.setData({
        showCancel: !showCancel
      });
    },

    async onConfirm() {
      const {
        type
      } = this;
      let res = null;

      switch (type) {
        case 0:
          res = await cancelOrder(this.id);
          break;

        case 1:
          res = await delOrder(this.id);
          break;

        case 2:
          res = await confirmOrder(this.id);
          break;
      }

      if (res.code == 1) {
        this.onShowDialog();

        if (type == 0 || type == 2) {
          Tips({
            title: res.msg
          });
          this.getOrderDetailFun();
        } else if (type == 1) {
          Tips({
            title: res.msg
          }, {
            tab: 3,
            url: 1
          });
        }

        event.emit('RESET_LIST');
      }
    },

    delOrder(e) {
      this.setData({
        type: 1
      });
      uni.nextTick(() => {
        this.onShowDialog();
      });
    },

    comfirmOrder(e) {
      this.setData({
        type: 2
      });
      uni.nextTick(() => {
        this.onShowDialog();
      });
    },

    cancelOrder(e) {
      this.setData({
        type: 0
      });
      uni.nextTick(() => {
        this.onShowDialog();
      });
    },

    payNow(e) {
      this.toast = Toast.loading({
        duration: 0,
        // 持续展示 toast
        forbidClick: true,
        message: '请稍等...'
      });
      prepay({
        from: 'order',
        order_id: this.id
      }).then(res => {
        Toast.clear();

        if (res.code == 1) {
          let args = res.data;
          wxpay(args).then(() => {
            Tips({
              title: '支付成功'
            });
            this.getOrderDetailFun();
            event.emit('RESET_LIST');
          }).catch(() => {});
        }
      });
    },

    getOrderDetailFun() {
      getOrderDetail(this.id).then(res => {
        if (res.code == 1) {
          const cancelTime = res.data.order_cancel_time * 1000 - Date.now();
            this.orderDetail = res.data
          this.$nextTick(() => {
              this.isFirstLoading = false
          });
        }
      });
    },

    goPage(e) {
      let {
        url
      } = e.currentTarget.dataset;
      uni.navigateTo({
        url
      });
    }

  }
};
</script>
<style lang="scss">
/* pages/order_details/order_details.wxss */
.order-details {
    position: relative;
    padding-bottom: calc(120rpx + env(safe-area-inset-bottom));
}
.order-details .header-bg {
    position: absolute;
    top: 0;
    width: 100%;
    height: 200rpx;
    background-color: $-color-primary;
    z-index: -1;
}
.order-details .contain {
    margin: 0 20rpx 20rpx;
    border-radius: 14rpx;
    background-color: #fff;
}
.order-details .header{
    padding: 24rpx 40rpx;
    box-sizing: border-box;
}
.order-details .header .van-count-down {
    color: #fff;
    margin: 0 10rpx;
}
.order-details .img-line {
    height: 1.5px;
    width: 100%;
    display: block;
}
.order-details .address-wrap {
    height: 164rpx;
    padding: 0 24rpx;
}
.order-details .order-info {
    padding: 12rpx 0;
}
.order-details .order-info .item{
    padding: 12rpx 24rpx;
}
.order-details .order-info .item .title {
    width: 180rpx;
    flex: none;
}

.order-details  .price > view{
    height: 60rpx;
    padding: 0 24rpx;
}
.order-details .footer{
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 100rpx;
    padding: 0 24rpx;
}

.footer .plain {
    border: 1px solid #BBBBBB;
}
.footer .plain.red {
    border: 1px solid var(--primary-color);
}

.tips-dialog {
    height: 230rpx;
    width: 100%;
}

.order-details .invite-btn  {
    background: linear-gradient(270deg, #FF2C3C 0%, #F95F2F 100%); 
    margin: 30rpx 26rpx 40rpx;
}
</style>

// app/src/pages/user/OrderDetails.tsx
import React from 'react'
import { ScreenProps } from '../../typing'
import { contain, rowEnd, row, getImageSize, rowBetween } from '../../constraint/Style'
import { StyleSheet, View, Text, ScrollView, Image, SafeAreaView } from 'react-native'
import Theme from '../../constraint/Theme'
import { icon_address, pay_line, arrow_right, icon_warning } from '../../constraint/Image'
import OrderGoods from '../../components/bussiness/OrderGoods'
import PressButton from '../../components/main/PressButton'
import { getOrderDetail, cancelOrder, delOrder, confirmOrder } from '../../api/user'
import { isSuccess } from '../../utils/request'
import PriceFormate from '../../components/bussiness/PriceFormate'
import Dialog from '../../components/main/Dialog'
import { Toast } from '@ant-design/react-native'
import { goBack, navigate } from '../../utils/navigation'
import { postEvent } from '../../utils/event'
import CountDown from '../../components/main/CountDown'
import { prepay } from '../../api/app'
import { WXPay } from '../../utils/wechat'
import { ScreenWidth } from '../../utils/app'

type OrderDetailsProps = ScreenProps<'OrderDetails'>

export default class OrderDetails extends React.Component<OrderDetailsProps, any> {
    [x: string]: any
    constructor(props: OrderDetailsProps) {
        super(props)
        this.id = props.route.params.id
        this.state = {
            orderInfo: {},
            showDialog: false,
            type: '',
            cancelTime: 0
        }
    }
    UNSAFE_componentWillMount() {
        this._getOrderDetail()
    }
    _getOrderDetail() {
        getOrderDetail(this.id).then((res: any) => {
            if (isSuccess(res)) {
                const cancelTime = res.data.order_cancel_time * 1000 - Date.now()
                this.setState({
                    orderInfo: res.data,
                    cancelTime: cancelTime > 0 ? cancelTime : 0
                })
            }
        })
    }
    orderHandel(type: number) {
        this.setState({
            type: type
        }, () => this.onShowDialog())
    }
    async _pay() {
        let payOpt: any = await prepay({
            from: 'order',
            order_id: this.id
        }, true)
        if (isSuccess(payOpt)) {
            let opt = payOpt.data
            WXPay(opt).then(() => {
                this._getOrderDetail()
                postEvent('REFLESH_ORDER')
            }).catch(() => {
                // Toast.info('支付失败')
            })
        }
    }
    async onConfirm() {
        const { type } = this.state
        let res: any = null
        switch (type) {
            case 0: res = await cancelOrder(this.id)
                break;
            case 1: res = await delOrder(this.id)
                break;
            case 2: res = await confirmOrder(this.id)
                break;
        }
        this.onShowDialog()
        if (isSuccess(res)) {
            if (type == 0 || type == 2) {
                Toast.info(res.msg)
                this._getOrderDetail()
            } else if (type == 1) {
                Toast.info(res.msg, 1, () => { goBack() })
            }
            postEvent('REFLESH_ORDER')
        }
    }
    onShowDialog() {
        this.setState({
            showDialog: !this.state.showDialog
        })
    }
    getDialogText() {
        const { type } = this.state
        switch (type) {
            case 0: return '确认取消该订单吗？'
            case 1: return '确认删除该订单吗？'
            case 2: return '确认收货吗？'
        }
    }

    orderStatusView() {
        const { orderInfo: { order_status }, cancelTime } = this.state
        let title = null
        let desc = null
        switch (order_status) {
            case 0: title = "等待买家付款"
            
                break;
            case 1: title = "等待商家发货"
                desc = "您的商品正在打包中，请耐心等待…"
                break;
            case 2: title = "已发货"
                desc = "您的商品正在路中，请耐心等待…"
                break;
            case 3: title = "已完成"
                desc = "商品已签收，期待再次购买！"
                break;
            case 4: title = "订单已关闭"
            // desc = "您的商品正在打包中，请耐心等待…"
                break;
        }
        return (
            <View>
                <View style={{ position: 'absolute', height: 100, width: '100%', backgroundColor: Theme.brand_primary, top: 0 }}></View>
                <View style={{paddingVertical: 15, paddingHorizontal: 20}}>
                    <Text style={{ fontSize: Theme.font_size_lg, color: 'white', fontWeight: 'bold' }}>{title}</Text>
                    {desc ? <Text style={{ fontSize: Theme.font_size_sm, color: 'white', marginTop: 5 }}>{desc}</Text> : null}
                    {cancelTime > 0 ? <View style={[row, { marginTop: 5 }]}>
                        <Text style={{ color: Theme.fill_base, fontSize: Theme.font_size_sm }}>支付剩余</Text>
                        <CountDown style={{ color: Theme.fill_base, fontSize: Theme.font_size_sm, marginHorizontal: 4 }} format="mm分ss秒" time={cancelTime} onFinish={() => this._getOrderDetail()} />
                        <Text style={{ color: Theme.fill_base, fontSize: Theme.font_size_sm }}>自动关闭</Text>
                    </View> : null}
                </View>
            </View>
        )
    }
    addressView() {
        const { orderInfo: {
            consignee,
            delivery_address,
            mobile
        } } = this.state
        return (
            <View style={styles.container}>
                <View style={[styles.addressWrap, row]}>
                    <Image source={icon_address} style={getImageSize(22)} />
                    <View style={styles.addressInfo}>
                        <View style={row}>
                            <Text style={{ fontSize: Theme.font_size_md, }}>{consignee}</Text>
                            <Text style={{ marginLeft: 8, fontSize: Theme.font_size_md, }}>{mobile}</Text>
                        </View>
                        <View style={{ marginTop: 5 }}>
                            <Text style={{ fontSize: Theme.font_size_sm, color: Theme.color_text_secondary, }}>{delivery_address}</Text>
                        </View>
                    </View>
                </View>
            </View>
        )
    }

    orderPrice() {
        const { orderInfo: {
            goods_price,
            shipping_price,
            order_amount
        } } = this.state
        return (
            <View style={styles.container}>
                <View style={[styles.priceItem, rowBetween]}>
                    <Text>商品金额</Text>
                    <PriceFormate price={goods_price} />
                </View>
                <View style={[styles.priceItem, rowBetween]}>
                    <Text>运费</Text>
                    <Text>+<PriceFormate price={shipping_price} /></Text>
                </View>
                <View style={[styles.priceItem, rowEnd]}>
                    <View style={row}>
                        <Text style={{ fontSize: Theme.font_size_base, color: Theme.color_text_secondary }}>实付金额：</Text>
                        <PriceFormate style={{ fontSize: Theme.font_size_xl }} color={Theme.brand_primary} price={order_amount} />
                    </View>
                </View>
            </View>
        )
    }
    orderInfoItem(title: string, content: string) {
        if (!content) return null
        return (
            <View style={[styles.orderItem, row]}>
                <Text style={styles.title}>{title}</Text>
                <Text style={styles.info}>{content}</Text>
            </View>
        )
    }
    getFooter() {
        const { orderInfo: { cancel_btn, pay_btn, delivery_btn, del_btn, take_btn } } = this.state
        return (
            <View style={[styles.footer, rowEnd]}>
                {cancel_btn ? <PressButton round={true} size="base" style={{ ...styles.btn, borderColor: Theme.border_color_base }} onPress={() => this.orderHandel(0)}>
                    <Text style={{ color: Theme.color_text_secondary }}>取消订单</Text>
                </PressButton> : null}
                {pay_btn ? <PressButton size="base" round={true} style={{ ...styles.btn, backgroundColor: Theme.brand_primary, borderWidth: 0 }} onPress={() => this._pay()}>
                    <Text style={{ color: 'white', }}>立即付款</Text>
                </PressButton> : null}
                {delivery_btn ? <PressButton round={true} size="base" style={{ ...styles.btn, borderColor: Theme.border_color_base, }} onPress={() => navigate('Logistics', { id: this.id })} >
                    <Text style={{ color: Theme.color_text_secondary }}>查看物流</Text>
                </PressButton> : null}
                {del_btn ? <PressButton round={true} size="base" style={{ ...styles.btn, borderColor: Theme.border_color_base }} onPress={() => this.orderHandel(1)}>
                    <Text style={{ color: Theme.color_text_secondary }}>删除订单</Text>
                </PressButton> : null}
                {take_btn ? <PressButton round={true} size="base" style={{ ...styles.btn, borderColor: Theme.brand_primary }} onPress={() => this.orderHandel(2)}>
                    <Text style={{ color: Theme.brand_primary }}>确认收货</Text>
                </PressButton> : null}
            </View>
        )
    }
    render() {
        const { orderInfo: {
            order_goods,
            id,
            shop,
            user_remark,
            order_sn,
            pay_way_text,
            create_time,
            pay_time,
            shipping_time,
            confirm_take_time,
            cancel_time
        }, showDialog } = this.state
        if (!id) return null
        return (
            <SafeAreaView style={contain}>
                <ScrollView style={{ flex: 1 }}>
                    {this.orderStatusView()}
                    {this.addressView()}
                    <View style={styles.container}>
                        <OrderGoods goods={order_goods} link={true} />
                    </View>
                    {this.orderPrice()}
                    <View style={{...styles.container, ...styles.orderInfo}}>
                        {this.orderInfoItem('卖家留言', user_remark || '无')}
                    </View>
                    <View style={{ ...styles.container, ...styles.orderInfo }}>
                        {this.orderInfoItem('订单编号', order_sn)}
                        {this.orderInfoItem('支付方式', pay_way_text)}
                        {this.orderInfoItem('下单时间', create_time)}
                        {this.orderInfoItem('付款时间', pay_time)}
                        {this.orderInfoItem('发货时间', shipping_time)}
                        {this.orderInfoItem('成交时间', confirm_take_time)}
                        {this.orderInfoItem('关闭时间', cancel_time)}
                    </View>
                </ScrollView>
                {this.getFooter()}
                <Dialog style={{ width: 260 }} isVisible={showDialog} onCancel={() => this.onShowDialog()} onConfirm={() => this.onConfirm()} >
                    <View style={{ alignItems: 'center' }}>
                        <Image source={icon_warning} style={getImageSize(28)} />
                        <Text style={{ marginTop: 15 }}>{this.getDialogText()}</Text>
                    </View>
                </Dialog>
            </SafeAreaView>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        marginHorizontal: 10,
        marginBottom: 10,
        borderRadius: 7,
        backgroundColor: Theme.fill_base
    },
    addressWrap: {
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    addressInfo: {
        marginLeft: 8,
        flex: 1
    },
 
    priceItem: {
        height: 38,
        paddingHorizontal: 12
    },
    orderInfo: {
        backgroundColor: Theme.fill_base,
        paddingVertical: 10,
    },
    orderItem: {
        paddingLeft: 12,
        paddingRight: 10,
        paddingVertical: 3
    },
    title: {
        width: 86,
        fontSize: Theme.font_size_base,
        color: Theme.color_text_paragraph,
        lineHeight: 20
    },
    info: {
        fontSize: Theme.font_size_base,
        color: Theme.color_text_paragraph,
        lineHeight: 21
    },

    footer: {
        paddingHorizontal: 12,
        backgroundColor: Theme.fill_base
    },
    btn: {
        width: 86,
        marginLeft: 10,
        height: 30,
        borderWidth: Theme.border_width_sm,
        marginVertical: 9,
    }

})
